@startuml
skinparam rectangle {
        backgroundColor<<NOTE>> yellow
        borderColor<<NOTE>> yellow
        fontsize<<NOTE>> 12
}
' top to bottom direction 
' left to right direction

package "P0" { 

    [P1 Gateway]
    rectangle "P0 需要给P2 提供如下内容:\n1.提供调度;\n2.提供volume path;\n3.对接P2的API;"  <<NOTE>> {

    } 
}

package "P1" {
    interface RPC as rpc
    interface "   HTTP" as http
    [P1 Gateway] .right.> http
    http - [P2]
    [P2] ..> rpc
    [P2] ..right.> openAPI : create snapshot
    rpc - [P3\n]
}

database "Storage" {
    openAPI -left- [P4]
    collections "disk files" as disk
    [P4] -down- disk
    [P3\n] ...right.> disk : copy data   
}
@enduml